#!/usr/bin/env bash

rootdir="$(cd "${0%/*}/.." && pwd -P)"

make_file() {
  local file="$1"

  # print the beginning of the file
  sed -ne '1,/^[ ]*$/ p ; /^me=/ p ;' ${file}

  # define the bindir variable as the install dir
  printf 'bindir="%s"\n\n' "${install_dir}"

  # print the utils includes
  sed -e '1, /^[ ]*$/ d' ${rootdir}/bin/utils.sh

  # print the rest of the file
  sed -e '1,/^source/ d' ${file}
}

main() {
  local name f dest install_dir="/usr/local/bin"

  mkdir -p ${rootdir}/build

  for f in "${rootdir}/bin"/fx*; do
    name="${f##*/}"
    dest=${rootdir}/build/${name}

    make_file "$f" > "${dest}"
    chmod +x "${dest}"
  done
}

main
