#!/usr/bin/env bash

rootdir="$(cd "${0%/*}/.." && pwd -P)"

main() {
	bats ${rootdir}/tests/unit || exit $?
	bats ${rootdir}/tests/integration || exit $?
	${rootdir}/tests/visual/run || exit $?
}

main
