#!/usr/bin/env bash

rootdir="$(cd "${0%/*}/.." && pwd -P)"

main() {
  local destdir="/usr/local/bin" name dest

  for f in "${rootdir}/bin/"fx*; do
    name="${f##*/}"
    dest="${destdir}/${name}"
    echo "uninstalling: $dest"
    rm "$dest"
  done
}

main
